name: Build & test

on: [push, pull_request]

permissions:
  contents: read
  
jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    uses: przemek83/workflows/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: ${{ matrix.platform }}
