name: Static analysis and coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  analyze:
    uses: przemek83/workflows/.github/workflows/static-analysis-and-coverage-cpp.yml@main
    secrets: inherit
